
<div class="inner-page-banner text-center">
       <div class="container pt-5 pb-5">
         <h1 class="banner-heading-inner">Our Terms &amp; Conditions</h1>
       </div>
    </div>

  <section>
    <article>
      

      <div class="container pb-5 pt-5">
          <h2 class="main-heading">Terms &amp; Conditions</h2>
          <p>Travel Fares respect your opinions and values your trust. Our main motive is to maintain the website to proffer our customers in collecting genuine travel information, making legitimate reservations, and determining the presence of travel-related goods and services. The following Terms and Conditions govern the website use. Using the website, you are obeying and agreeing with these terms and conditions and agreeing that Travel Fares controls all the travel reservations.</p>
          <p>We promise to use reasonable, organizational, administrative, and technical measures to preserve your important information with us. We cannot assure 100% security of the storage system and data transmission. Thus, if you felt that your account security had been compromised, notify our customer executive to resolve your issues and take action regarding your concern.</p>

          <h3>General Disclaimer</h3>
          <p>Travel Fares is not at all a principal party. Still, the company acts as an aggregator. It tends to make all the necessary arrangements with all the third-party vendors, such as cruise lines, railroads, airlines, car rental agencies, hotel consolidators, traveler assist service travel suppliers and insurance providers. Most of the travel-related activities and services include air transportation, without limitation, car rental, and lodging.</p>

          <p><b>By using this website, our customers acknowledge that:</b></p>
        <p>The rate proffered by Travel Fares.com and our affiliate companies is almost the result of negotiation between the travel suppliers and Travel Fares and consists of all the necessary fees retained by suppliers for their taxes, services, and other charges</p>
        <p>When you are booking tickets with any of the Travel Supplier via this website, you authorize Travel Fares and affiliate companies to book the flight reservations and enter a contract on the passenger's behalf with our travel suppliers for the exact price displayed, consist of applicable taxes, fees, and charges of Travel Fares services and suppliers</p>
        <p>Travel Fares is not liable for inaccuracies on the website and errors or the failure of travel suppliers from whom you can acquire travel services via this site.</p>
        <p>Travel Fares is not liable and accountable for any act of injury, omission, error, irregularity, nonperformance, damage, accident, loss, or any other action that might have happened due to inaction, default, neglect of any Travel Supplier.</p> 
        <p>Travel Fares agrees that there can be any fluctuation in the schedule, price, equipment, or accommodations for travel service after booking and payment that the company and the customers.</p>
        <p>Travel Fares is not responsible and accountable for overbooking, cancellation, re-routing, strike, and delaying any weather or government occurrence. It might affect your flight reservation made with Travel Fares.</p>
        <p>Travel Fares is not liable for any currency rates and conversions when paid once you made your travel reservations for international service or products with us. You acknowledge and agree with the currency rates vary, and the quoted price available on the website in the local currency is given in the guideline and not binds on our organization or the travel supplier.</p>
        <p>Once you paid for individual travel reservations, it might be completely non-refundable, or it might involve a penalty in seeking a refund or cancellation from the travel supplier of travel products and services. We do not have any control over the printed price there on the air tickets.</p>
        <p>Discounts available on the site proffered may vary; it depends on varied factors such as a class of service, airlines utilized, time of year, destination, minimum stay requirements fulfilled, advance notice provided, and flight load.</p>
        <p>Travel Fares does not have any control over the travel advertiser's products and services advertised on our website. We do not promise or give a guarantee, validate, promote or endorse any of them.</p>
        <p>A contract is made between the travel supplier and the customer once you are done with the booking, and additional terms and conditions are applied to the purchase of travel goods and services and your travel booking. We advise our customers to read out all the other Terms and Conditions given by Travel Supplier.</p>
        <p>In some cases, some of the Travel suppliers might ask you to cover some additional expenses incurred during the use of the products and services or your stay via your cash payment or credit card. Such deposits are not related to any of the payments received by Travel Fares for car, airline, hotel, or ticket booking.</p>
        <p>Travel Fares believes that our passengers must understand that any violation of a Travel Suppliers rules and regulation might result in cancellation of your air ticket reservations.</p>
        
        <h4>Waiver</h4>
        <ul class="list-names">
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Using the website, you must agree that neither Travel Fares nor our affiliates, subsidiaries, officers, managers, directors, agents, employees, contractors shall be liable for the following points.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Any damage or loss made to the property or injury to any person caused due to the reason of any negligence, defect, or any other wrongful act or omission or any performance failure by any Travel Supplier.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Any loss of enjoyment, inconvenience, mental distress, or other similar matter;</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Any missed connections, delayed departure, terminations of service, substitutions of accommodations, or changes in air rates and fares.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Any double-booking of air reservations and cancellations or air tickets beyond the reasonable control of Travel Fares: and</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Any claim made of any nature arising out of or connected with transportation or air services, products, or other features performed or not, occurring or not concerning your itinerary</li>
        </ul>

        <h5>Privacy</h5>
        <p>Be sure that your debit, credit, or charge card is not being used without your permission; we will have to verify your personal information, name, contact number, address given by you during the flight booking process against the third party databases. By accepting the above-stated Terms and Conditions, you agree and authorize our organization to carry out the verifications checks. Before performing the security checks of Travel Fares, you concur with the essential details provided by you, and you are liable to reveal them to a Registered Credit Reference Agency. You can keep a record of important information in whole or a part of it. This verification process is done for the only purpose of confirming and verifying your identity, and this process does not let you perform any credit rating or credit check will not get affected. You must agree that you must be of 18 years of age and should possess the legal authority to be part of this agreement and use the website concerning the Terms and Conditions. All the details provided by our customers to us is secured with us and processes in strict accordance with the act, Data Protection Act 1998.</p>
        <p>With the terms and conditions, you agree to, and you gathered information about the website, which is only made for travel reservations and travel purchases for you or another person. You are responsible and liable to act legally.</p>
        <ul class="list-names">
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Our customers agree to acknowledge that if you abuse or overuse the travel facilities or services available on the website, access to travel facilities may be denied.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> The website is not being used for any commercial purpose.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> You agree that you will not monitor, copy, or access any details or content of our website.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> You will not disguise the website information origin that you transmit via this website when you want to navigate the website by doing any travel booking, post, and reservation of any content.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> We have the right to cancel your Travel Fares availed services and account, and even we can terminate your website use if we find you violating the above terms in any case.</li>
        </ul>
        
        <h5>Booking process</h5>
        <p>For completing the Booking, you need to follow the below steps to ensure its validity: When Travel Fares places Service Elements, which, means we are welcoming you to make an offer for your purchase. The passengers cannot make this offer until they press the button on the website's payment page (titled with Book and Review Trip Details) given on the Site. Once you have accepted, you have made Travel Fares an offer ( which will not alter if you change your mind) to buy the genuine Service Element (s) from the relevant Travel Suppliers. We have authority to accept or reject your offer, on Travel Supplier's behalf, at our sole discretion.</p>
        <ul class="list-names">
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> The Travel Fares email confirmation is proof that we have got your offer and it is not the contractual acceptance of your travel booking. Our organization will only confirm your booking once we will check out the relevant Service Elements' availability.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Your Booking will be processed once the relevant Service Element is available. When we received the complete payment then only your relevant Booking is formed.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> The travel contract between the related travel supplier and the customer will only contain the Service Elements given conformity via email with the ticket numbers.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> The terms of your ticket booking like price, date of your travel, tickets availability are not guaranteed till the form between travellers and travel supplier, and the concerned Travel Supplier has given the relevant air ticket.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Please note down that after completing the whole Booking stage you are liable to cancel or alter the details like your name or destinations of your ticket booking if any such things are permitted in relation with these terms and conditions.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> All the travellers strictly need to travel on the same itinerary after booking the air tickets ( for more than one travellers). Any addition or changes cannot be done to your ticket booking. Adding or eliminating passengers from your ticket booking is not possible.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Travel Fares has the right to check and correct your errors in any advertised pricing. If applicable, passengers will give an option to either allowed Travel Fares to collect an amount equal to increased price from customers credit or debit card or cancel the Booking, before your departure.</li>
        </ul>
        
        <h5>Pricing, Taxes/Fees, and Payment:</h5>
        <p>The quoted "Total Price" consists of all the applicable fees and taxes in your Booking. We request our passengers to check your ticket confirmation or read out Travel Fares Terms and Conditions wisely for an additional charge that is not there on the website. The cost of additional seat reservation, baggage, fuel surcharges, security, hotel incidentals and other applicable service charges may be appropriate by the relevant Travel Supplier, and you can charge during the check-in time. Travel Fares holds no accountability or responsibility for such charges. You are solely responsible for such additional costs that were due to the Travel Supplier. If you have any issues or questions related to such charges, do contact the Travel Supplier directly, before starting your trip.</p>
        <ul class="list-names">
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Payment must be made with your valid debit or credit card at the time of your flight booking. Travel Fares accepts your debit or credit cards with a verified billing address.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> This gives to authority to Travel Fares and its authorized third party the credit charge or debit card you provide to us for the total Booking price.</li>
        </ul>
        
        <p><b>All prices, offers and conditions of the total sale may subject to:</b></p>
        <ul class="list-names">
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Change without prior notice,</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Purchase in advance, seating, eligibility or other limitations;</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Travel dates, days, maximum or minimum stays, seasons, holidays, stopovers, blackout dates, and waitlisting restrictions.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Upto one-year reservation validation limitations (if any penalties/ restrictions, extension permitted may apply).</li>
        </ul>
    
        <h5>Availability</h5>
        <p>A travel reservation is not completed until the tickets have been issued or confirmed. To secure our customers, we gather your debit/credit card number and send you a verification code. Once we have received your verification number, we check the same from the debit/credit card company regarding its authenticity, and thus we confirm that charge/ debit can be accepted by you. Until the card authenticity is verified, the airfares are subject to change. For any reason, if passengers debit/credit card gets declined by the travel provider/ issuing company, that results in a declined transaction, Travel Fares shall not be held accountable for the same. We do not guarantee fluctuation in the airfare prices during the verification process, in case, the airfare is not there, we will issue a code for your credit card approval. If the transaction is not finished, it may be possible that the approval code might be temporarily credited the price from your given bank account.</p>
        
        <h5>Promo Codes</h5>
        <ul class="list-names">
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Travel Fares will issue some promo codes that are almost valid for online bookings and online travel reservations. However, some of the Travel Fares promo codes might be applied over the call through our customer service centre.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Travel Fares invites its travellers to sign up its newsletter to acquire promo codes via email.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> The maximum discount from all the Travel Fares promo codes is the value of our Traveler assist fees and service fees (up to 70%).</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Travel Fares promo codes are almost non-transferable, cannot hold cash value, cannot be bartered or sold.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> On the payment page, you must enter a valid promo code on promo code link to gain the discount's value. In case the code is not working or entered, you cannot redeem the deal and has no value. If the technical problem occurs and a coupon link is not there, or the code is not accepted, passengers have the right not to buy any product or service, but in no circumstances, no credit will be applied after the purchase is made.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Travel Fares promo codes offer might be withdrawn or revised at any time without prior notice, even if any of the websites are providing the same offers.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> You don't have any recourse; only you cannot make the purchase</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Once anyone withdraws the offers, the promo codes get invalid, and the system and the website will not take any promo code when entered. In this situation, you have the right to continue with the original price or can stop your purchase.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> The final price will be displayed with or without any promo, or discount code will be the amount charged or billed, and no credits and discounts will be applied to the purchase made for any reason.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Travel Fares will not combine its promo codes with any other offer.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Travel Fares can decline your transaction that consists of an error in the promo code value, even your booking is created, and its receipt is issued.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Due to any reason, if your credit/ debit card or another form of payment is not being accepted or processed, we will notify you within 24 hours ( or might be in case of non-debit/ credit card payment methods, we can inform you within more than 24 hours' time period.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> If there is any other change or change in airfare price, will notify you about the difference before your payment is processed and accepted and you are eligible to accept or reject the transaction. If you select to rescind the transaction, you will not be charged.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> One we accept your payment via your credit/ debit card and it is being processed, we guarantee that we will honour the total quoted price of the air tickets, even if there is any alteration or fluctuation in the airfare price.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> To assist you with further protection, Our system will determine the high-risk transactions. We will not process it unless we are directed to resume such transactions after we get assurity from our credit-card verification team about the safety. We might coordinate with you or your bank, to regain the validity of such transactions.</li>
        </ul>
    
        
        <h5>Ticket delivery</h5>
        <p>Most tickets are electronic (e-Tickets), but by chance with some itineraries, if an e-Ticket is not there, a paper ticket will be issued to the passengers. We advise you to check out the shipping charges before booking tickets and pressing the "confirm button." In case, Travel Fares has made the delivery of another product or service or could not issue your e-ticket for a particular reservation. Travel Fares will send you the paper ticket of your selected service or product via a secure mode of delivery from a reputed courier company. The credit holders will be debited with the shipping charges present on the website.</p>
        <p>The shipping charges are displayed on the site before you make your travel booking, and you might not elect to buy the tickets to avoid the shipping charges. Travel Fares is not accountable and responsible for the fault made by the delivery company. We will try our best to redeliver your product or service but cannot promise to redeliver on time. In case you provide us the incorrect delivery address, you have to give extra charges to the Delivery Company to alter the actual address. You might be billed to the credit card used for the travel payment. If an e-ticket is generated, all the ticket details will be displayed on the website.</p>
        

        <h5>Baggage Policy and Fees</h5>
        <p>The airlines will ask you to pay some extra charges for some specific services at the airport or in case you have crossed the airline's limits mentioned on the website. One of such activities is weight allowed or no of airbags allowed in the airlines, as some of the airlines do not proffer free baggage allowance. Travel Fares will give you a detailed summary of key terms used in an airline's baggage policy during air ticket booking. Still, you must consult the experts of each airline about their baggage and ancillary fees details.</p>
        
        <h6>OverBooking of Flights</h6>
        <p>Sometimes it is possible those airline flights may be overbooked due to heavy rush or might be the seat booked by the customer is not there on the flight. Airlines deal with these scenarios as per their respective rules and regulations, present in the airline's contract of carriage. Check with the airline's official site or call our expert for more details.</p>

        <h6>Unaccompanied minor</h6>
        <p>Travel Fares does not sell air tickets to unaccompanied minors 18 years and under. Different airlines have different rules, policies for the minor traveling without an adult. Below are some pointers that may change with the airline directly for minor age requirements.</p>
        <p>Some airlines will not permit unaccompanied minors to travel without adult supervision. Many of the non-stop flights will not permit unaccompanied minors to travel. Many airlines might ask you to give additional fees at the time of check-in.</p>
        <p>You must call the airline experts to guide you with rules and regulations for an unaccompanied minor traveling without an adult supervision.</p>

        <h6>Visa and Entry Requirements</h6>
        <p>We advise our worthy passengers to get their verification done for the travel documents (entry visa/transit visa) for their respective country from which they are entering or transmitting. Check out the authentic guidelines and information about international travel and documents at www.travel.state.gov and also with the embassy/consulate of the country you are transiting or entering, visiting through. Travel Fares is not held responsible if you do not have proper travel documents and deny transit or entry into a country.</p>
        <p>Your transaction with Travel Fares does not give any surety for your entrance to the country of destination. Passengers must understand that Travel Fares is not held responsible for stating passengers' eligibility to transit or enter any particular country. Information made by any Travel Fares employee tends to be verified with government authorities. Such information does not imply any responsibility on Bookfare's behalf.</p>

        <h6>General Restrictions</h6>
        <p>All the flights must be confirmed with the airline, as they might have some last-minute schedule alterations. Travelers must re-confirm the schedule atleast 24 hours before departure for domestic flights and 72 hours prior for Hawaii flights and international destinations.</p>
        <p>Airlines are strictly responsible for Upgrades/ standby. In most cases, standbys and upgrades are not permitted</p>
        <p>Most of the discounted tickets are not allowed for frequent flyer mileage accrual.</p>
        <p>The entire request related to flight seats will be forwarded to the respective airlines. We advise you that all seat requests are not guaranteed by the airlines. If you tend to have immediate response or confirmation on your air seat or want to have special requirements like a wheelchair or stretcher, please contact airline professionals.</p>
        <p>We have the right to cancel passengers' requests for travel to those destinations that have been embargoed by the United States government.</p>
        <p>A traveler's departure tax or duty may be assessed upon departure via international places like UK, Australia, the Caribbean, and Mexico. These are some of the local government taxes taken at the airports, and they are excluded in initial ticket costs. Almost $ 28 administrative fees will be taken for bookingswhose travel receipt is made a year or more than a year ago.</p>
        
        <h5>Responsibility</h5>
        <p>Travel Fares has made all the arrangements with the third-party suppliers for the accommodations, tour and travel packages services and lodging, air transportation, and car rental. Travel Fares is not the agent of the travel supplier assisting with travel-related services or of the customer. By using this website, you agree and waive claim against Bookfare, its affiliates, subsidiaries or directors, agents, party officers, employees, or contractors, shall be accountable or liable for:</p>
        <ul class="list-names">
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Any damage or loss made to the property or injury to any person caused by negligence, defect, or other wrongful act of any failure of performance, the wrongful act or omission by any other vendor, transportation company, or supplier.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Any loss of enjoyment, inconvenience, mental distress or other similar instances.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Any missed connections. Delayed departure, substitutions of accommodations, change in fares and rates, or termination of service.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Any double booking or cancellations of tickets or reservations are beyond the reasonable control of Travel Fares.</li>
            <li><svg xmlns="http://www.w3.org/2000/svg" width="16px" height="16px" fill="#333" viewbox="0 0 512 512"><title>Chevron Forward</title><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M184 112l144 144-144 144"></path></svg> Any claim of any nature connected with air or other transportation or arising out, services, or varied features occurs or performed in connection with any package component. Your sole remedy is with the particular Travel supplier in concern with your claim for that travel product/ service, and it is not with Travel Fares.</li>
        </ul>

        <p>Travel Fares suggests you buy travel protection, which will help you recover specific change and cancellation fees. Travel Fares suggests purchasing travel protection via our travel protection provider by summing up the trip protection to your Travel Fares tour package. The payouts of Travel protection are subject to limits of coverage. Please read out the "Travel Protection Terms and Conditions" for relevant details. Any change made to travel plans will lead to a change in your coverage. If your plan changes, connect with our travel protection provider to confirm your policy's adequacy coverage.</p>
        
        <h5>Documents:</h5>
        <p>Electronic documentation and confirmation will be delivered to the email address on record unless otherwise stated.</p>
    
        <h5>Miscellaneous general terms and conditions</h5>
        
        <h6>Authority to send communication</h6>
        <p>By using the website in terms of making a travel booking or reservation, or sanctioning a transaction, you permit Travel Fares to send you communication in the way of postal mail, instant messaging, phone call, email or any different form of paper or electronic communication. These communications will have a prime focus on customer service and may consist of special offers.</p>
        
        <h6>Termination</h6>
        <p>We reserve the right, in our sole discretion and can terminate your access to full or part of the website, without liability, with or without prior notice, for no or any reason.</p>
        
        <h6>Severability</h6>
        <p>These mentioned Terms and Conditions are severable. Suppose any provision is stated to be invalid or unenforceable. In that case, such provision shall nonetheless be enforced to the fullest extent have permission by applicable law, and such determination shall not affect the enforceability and the validity of any of the remaining provisions.</p>
        
        <h6>No waiver</h6>
        <p>No failure on the part of Travel Fares will enforce any part of the stated Terms and Conditions. It shall consist of the waiver of Travel Fares rights under these mentioned Terms and conditions, whether for the past or the upcoming actions on the part of any person. Neither the travel receipt of any of Travel Fares funds nor the reliance of any person on Travel Fares actions shall be deemed to constitute a waiver of any terms and conditions part. Only an individual, written waiver having the signature of Travel Fares authorized representative shall have any legal effect.</p>
        
        <h6>Data scraping</h6>
        <p>If in case you abuse this website with varied scams, screen scraping, data scraping, we have the right to terminate the passenger access to our website immediately, without any notice.</p>
    
        <h6>No relationship</h6>
        <p>Nothing in the terms and conditions shall be constructed or deemed as creating a partnership, joint venture, employment relationship, independent contractor between us or any of our parties hereto based on making bookings travel reservations or using the website. Neither you nor Travel Fares is, under these Terms and Conditions, employee or legal representative of the other party, authorized as an agent. No party has the authority or power to commit or bind any other party.</p>
    
        <h6>Exclusive savings and discounts</h6>
        <p>Travel Fares offers varied fantastic discounts and saving opportunities for its passengers to make their travel experience hassle-free, comfortable, and pocket â€“friendly. Airfares, savings claims, and exclusive discounts are based on various factors, including gapping for more than 600 airlines to get the lowest available fare. We proffer some amazing deals to youths and seniors as you might find some discounted fares suggested by several airlines. The Travel Fares coupon codes are valid for savings to qualify ticket reservations off our standard service fees. Bereavement, visually impaired travelers, and Military members are eligible for discounts off Travel Fares reservation service fees.</p>
        <p>As compared to published fares, claims of savings on average traveler's savings are best. .Whereas saving claims and discounts depend on comparing the average fees for the same month or some other time frame that indicated airlines offers for the same routes or destination or adjacent months last year savings.</p>
    
        <p>All the savings displayed are against average ticket airfares present on Travel Fares.com for airfares current in a similar travel period. Fares consist of fees and taxes, fuel surcharges, and our service fees. Tickets are non-transferable, non-assignable, and non-refundable. You are not allowed to make changes to the name. The fare displayed on the site depends upon historical data is subject to change and cannot be guaranteed at the time of flight reservations. There is a greater possibility of seats being there at this fare on Tuesday, Wednesday, and Thursday. If you want to travel and enjoy the lowest fares, book your tickets in advance for almost upto 21 days. Weekend holidays and travel may have a separate surcharge. Passengers can save a bundle by comparing multiple airlines with Travel Fares.com and opt for the lowest available fare.</p>
        <p>We advise you to enter the discounted promo code at the time of check out. The promo code proffers passengers with exclusive offers and discounts.</p>
    
    
    </div>
    </article>
  </section>
